# TIPO DE DADO BOOLEANO (TRUE E FALSE)
# APENAS DOIS VALORES (0 E 1)
# O OPERADOR IGUAL (==) VÊ SE É IGUAL A OUTRO.


# RETORNA TRUE
print(10 == 10)

# RETORNA FALSE
print(10 == 53)

# PARA SABER O TIPO DE DADO
print(type(13 < 12))